name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
    - name: Run
      run: |
        cd api
        python run.py &

    - name: Wait for Flask server to start
      run: sleep 10s

    - name: Run test cases
      run : |
        pwd
        cd api/tests
        python fyers_login_test.py
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy with rsync
        uses: BuildPC/rsync-with-ssh-github-actions@master
        env:
          HELLO: cool
          MESSAGE: hello world
        with:
          key: ${{ secrets.SSH_KEY_NEW_DEPLOY }}
          host: example.com
          port: 22
          user: john
          destination: /var/www/
          # runs this on remove server
          ssh_before: |
            echo $HELLO
            echo $MESSAGE
            ls -lath

          # then run these commands
          ssh_after: |
            echo $HELLO
            echo $MESSAGE
            ls -lath
